const ENTRIES = [
    // === PRE-CHAPTER 1 (Negative sortOrder = left of Chapter 1) ===
    {
        id: "ms-pre-1",
        type: "main_story",
        title: "Pre-First Invasion",
        era: "Pre-First Invasion",
        timeline: "+100 BC1 (Before Chapter 1)",
        sortOrder: -110,
        summary: "",
        content: "The World was similar to what we know now in real life, but slightly more technologically advanced. <ul><li>Manufactures such as Elysion, Missilis and Tetra existed but no exact detail on how big they were aside from Relics stating them to be enterprises. (Early Relics called them by Elysion Enterprises, Missilis Industries, and Tetra Entertainment).</li><li>Military strength similar to IRL or at least slightly more advanced.</li><li>Einkk stated that she is roughly 20 years old (Memory of Goddess secret cutscene) which puts her origins during Pre-First Invasion but no other specifics on who or what made her.</li><li>Based off Chapter 43, the Vatican Theraputic Research Center (V.T.C.) had existed for a very long time and made many strides in the advancement of technology such as being able to cure afflictions, regrow limbs, and having the ability to transfer one's consciousness into another body. These 'miracles', as they people called them, brought in many devout followers which eventually made them very influencial throughout the known world.</li></ul>",
        locations: ["Earth"],
        tags: ["Humanity", "V.T.C."],
        image: "images/Chapter Thumbnails/Sky2.png",
        youtube: "",
        connections: []
    },
    {
        id: "ms-pre-2",
        type: "main_story",
        title: "The First Invasion",
        era: "The First Invasion",
        timeline: "100 BC1 (Before Chapter 1)",
        sortOrder: -100,
        summary: "",
		content: "<ul><li>Raptures began to invade multiple countries in hordes causing devastation.</li><li>Theories concluded that Raptures originated from the Space Station. Said theories were reinforced when it was discovered that the Raptures targeted various shuttle-launch locations around the world during the initial attack. <em>(RED ASH)</em></li><li>Initial military response was ill-equipped and resulted in many casualties.</li><li>The use of thermonuclear weapons had little to no effect and some instances had Raptures firing it back at humans. <em>(OLD TALES)</em> <em>(GLUTTONY)</em></li><li>As a result of all these attacks, The United Forces of Humanity (U.F.H.) was formed to be a combined effort against the Rapture threat.</li><li>The V.T.C. would aid the U.F.H. in the war against Raptures by utilizing their technological advancements in order to create Nikkes.</li><li>The first Nikke, Liliweiss, was created which followed the 1st and 2nd Generation Grimms models as well as the Mass-Produced models.</li><li>Previously a mercenary, The Legendary Commander began to acquire fame and eventually became the commander for the newly formed Goddess Squad.</li><li>Humanity began to win against Raptures as Nikkes proved to be an effective weapon, but due to that Raptures began to evolve.</li></ul>",
		locations: ["Earth", "Space Station"],
        tags: ["Humanity", "U.F.H.", "V.T.C."],
        image: "images/Chapter Thumbnails/SpaceElevator.png",
        youtube: "",
        connections: [
            { target: "ms-pre-1", type: "curved" }
        ]
    },

    {
        id: "ms-pre-3",
        type: "main_story",
        title: "Death of the First Grimms Model",
        era: "The First Invasion",
        timeline: "Unknown Time BC1 (Before Chapter 1)",
        sortOrder: -99,
        summary: "",
        content: "<ul><li>No specific info on <strong>Grimms Model 1</strong> yet. <em>(Red Ash Relic)</em></li><li><strong>Dorothy</strong> joins Goddess Squad as <strong>Grimms Model 2</strong>. Daughter of a politician, she wants the world to go back to the way it was before the Rapture Invasion.</li><li><strong>Rapunzel</strong> joins Goddess Squad as <strong>Grimms Model 3</strong>. A former leading candidate for the papacy, she wanted to become a beacon of hope for mankind and joined up.</li><li><strong>Snow White</strong> joins Goddess Squad as <strong>Grimms Model 4</strong>. Introduced herself to the squad during one of their battles by mending their weapons. Has met <strong>Liliweiss</strong> before but not stated when exactly. Initially wasn't confident enough to properly meet them and shut herself in her room crafting weapons.</li><li><strong>Red Hood</strong> joins Goddess Squad as <strong>Grimms Model 5</strong>. Making a dramatic entrance by appearing out of a box, Red Hood's introduction to the squad left a significant impression on them.</li></ul>",
        characters: ["Liliweiss", "Andersen", "Grimms Model 1", "Dorothy", "Rapunzel", "Snow White", "Red Hood"],
		locations: ["Earth"],
        tags: ["Humanity", "U.F.H.", "V.T.C.", "Goddess Squad"],
        image: "images/Event Thumbnails/Grassland.png",
        youtube: "",
        connections: []
    },
	
	{
        id: "es-001",
        type: "event_story",
        title: "New Year New Sword",
        era: "The First Invasion",
        timeline: "99 - 96 BC1 (Before Chapter 1)",
        sortOrder: -98,
        summary: "",
		content: "While the initial scenes are set during the present, the event story is set sometime after the First Invasion and before the events of Nonsense Red and Red Ash. <br><br><strong>Encounter Under the Moonlight: B</strong><br><br><ul><li>Scarlet reveals to the Commander that she had a sister and was part of a Nikke squad called Melee Squad.</li><li>The Commander is also curious on how she's able to remember due to having a mind switch. Scarlet specifies that she lost a majority of memories, but not all of them. She further elaborates that although she had to endure multiple mind switches, some memories can never be forgotten.</li></ul> <br><strong>Sisters of the Sword: A</strong><br><br><ul><li>Scarlet and her sister Rose, and 8 others are among the few selected for an experimental Nikke squad called Melee Squad for infiltration and reclamation.</li><li>Rose is selected to be the squad leader for having the highest test scores.</li></ul> <br><strong>Sisters of the Sword: B</strong><br><br><ul><li>The Melee Squad is deployed on their first mission to infiltrate and eliminate a Rapture lair. Despite the hesitancy of some of the Nikkes, their first mission resulted in a resounding success with zero casualties.</li></ul> <br><strong>Painting a Bright Future: A</strong><br><br><ul><li>In the following weeks, more missions continued to succeed, but more Nikkes were lost. Some Nikkes were even prone to mind switches due to attacking Raptures in head-on confrontations.</li><li>Due to their successes, they were officially sanctioned as a squad and were allowed to request support from other squads and manage their own more sustainably.</li><li>When Rose goes to confront the Lieutenant about when the additional supplies will be sent, he replies that the situation in the war is deteriorating so it's expected for the supplies to be delayed and encourages them to work harder in order to gain more priority in receiving the supplies.</li></ul> <br><strong>Painting a Bright Future: B</strong><br><br><ul><li>As the squad camps for the night, Rose and Scarlet share some alcohol and converse.</li><li>Rose ponders on how they remember each other as sisters despite not being Grimms Models since Mass-Produced Models either remember everything or nothing at all with the latter being more frequent.</li><li>They continue to converse about each other's plans after the war along with what the other squadmates would like to do. While Rose seems to want to be a free spirit and go where her heart takes her, Scarlet would want to spar with Rose while not wearing any armor.</li></ul> <br><strong>Nothing is Eternal</strong><br><br><ul><li>On numerous occasions, Rose and Scarlet had to cut down their own squadmates due to them having a Mind Switch.</li><li>Due to how their bodies were made, they were more susceptible to getting injured or dealing with multiple malfunctions. Aside from that, they were more likely to get Mind Switches since they dealt with Raptures in close combat.</li><li>Including both Rose and Scarlet, the Melee Squad was down to six members at this point in the story. Rose begins to question the validity of their circumstances and goes to question the Lieutenant.</li></ul> <br><strong>Seed of Discord: A</strong><br><br><ul><li>Rose and Scarlet approach the Lieutenant about the supplies and is told that it's still hard to acquire supplies since everything is in shambles out there. Rose interjects by saying that the squad they met previously had an adequate amount of supplies and noticed how unusual it was that their own was deprived of such.</li><li>The Lieutenant deflects her discovery and instead tells them that the other squads must have had accomplished more missions than they have. He then informs that they're assigned another mission and stresses that if they want the support they deserve then they'll have to put in the work.</li><li>As Rose and Scarlet approach the door to leave, the Lieutenant requests to speak to Rose alone. Scarlet leaves as Rose stays behind.</li></ul> <br><strong>Seed of Discord: B</strong><br><br><ul><li>Rose proposes to Scarlet about inciting a rebellion since she believes that support isn't coming and they need to do anything necessary to keep themselves alive. When asked about the private conversation with the Lieutenant, she merely states that he only told her a list of complaints like always.</li><li>From the mission briefing, they are to retake an arms depot but is far more difficult than anything they've done before considering their numbers it's relative to a suicide mission.</li><li>Rose consulted with the other members of the squad of going through with a rebellion with two agreeing with her and two opposing her, Scarlet also opposes the idea which makes the decision split.</li><li>Scarlet urges Rose to reconsider and to just go along with the mission, citing that even after they go through with the rebelling and get the support they'll be branded as traitors and eventually be killed off. She also tells her that she'd rather decide how she lives than obsess on how she dies, which moves Rose to acknowledge how much Scarlet has grown and decides to go along with the mission and convince the others.</li></ul> <br><strong>Like a Flower in Bloom: A</strong><br><br><ul><li>Scarlet attempts to sleep for the night but is awoken to the sound of someone banging on her door alerting about Rose but is cut off mid-way. When Scarlet opens the door to investigate, she finds one of her squadmates on the floor while two others are staring at her blankly. In her dying words, the fallen squadmate tells her that Rose went to kill the Lieutenant and she should hurry to stop her. The other two draw their swords to impede Scarlet's path, to which she does the same.</li></ul> <br><strong>Like a Flower in Bloom: B</strong><br><br><ul><li>A few hours prior during the private conversation with Rose and the Lieutenant, she discovers that the original intention from the U.F.H. was to slowly kill off the Melee Squad until only one was left which then would succeed to becoming a Grimms Model and that support was intentionally cut off in order to facilitate that objective.</li><li>The Lieutenant then gives her an ultimatum to kill off everyone painlessly since they're destined to die regardless. Rose ponders on what to do after learning all of this information.</li><li>Fast forwarding ahead to Scarlet going to intercept Rose, she discovers Rose standing alone while drenched in human blood.</li></ul> <br><strong>Fleetly Fading: A</strong><br><br><ul><li>Within the room, Scarlet sees the dead Lieutenant and one of her fallen squadmates. Rose reveals that she killed the Lieutenant by covering her eyes with a red strip of cloth and imagined him as a Rapture core in order to trick her brain and prevent a mind switch from happening. The fallen squadmate was collateral damage since Rose only intended to kill the Lieutenant.</li></ul> <br><strong>Fleetly Fading: B</strong><br><br><ul><li>Seeing the destruction that Rose had caused, Scarlet had no choice but to fight. Eventually she kills Rose by stabbing her sword through her core, but also finds out that Rose intended to kill herself off to save Scarlet.</li><li>As time passed the UFH became aware of what transpired and deemed the project a failure, citing that it was internal conflict that had the Nikkes kill each other.</li></ul> <br><strong>To my Beloved Sister</strong><br><br><ul><li>Scarlet took Rose's sword, Fleetly Fading, since her original sword was taken along with Rose's body. Although Fleetly Fading was broken, Scarlet met a blacksmith (Snow White?) that could fix it by using Rose's Core.</li></ul>",
		characters: ["Scarlet", "Rose"],
        locations: ["Earth"],
        tags: ["New Year New Sword", "U.F.H.", "Goddess Squad", "Melee Squad", "Scarlet", "Rose"],
        image: "images/Event Thumbnails/NYNS.png",
        youtube: "",
        connections: []
    },

	{
        id: "es-002",
        type: "event_story",
        title: "Nonsense Red",
        era: "The First Invasion",
        timeline: "99 - 96 BC1 (Before Chapter 1)",
        sortOrder: -97,
        summary: "",
        content: "",
        characters: ["Liliweiss", "Andersen", "Snow White", "Scarlet", "Rapunzel", "Dorothy", "Red Hood"],
        locations: ["Earth"],
        tags: ["Goddess Squad"],
        image: "images/Event Logos/Nonsense_Red_logo.webp",
        youtube: "",
        connections: []
    },
	
	{
        id: "es-003",
        type: "event_story",
        title: "Old Tales Part 1",
        era: "The First Invasion",
        timeline: "96 BC1 (Before Chapter 1)",
        sortOrder: -96,
        summary: "",
        content: "<ul><li>Set around shortly before and the same time as Red Ash.</li><li>Cinderella, Red Shoes, Siren, Hansel and Gretel are all created by Abe, a renowned V.T.C. scientist.</li><li>Raptures are being created faster than being killed, the projected number of Raptures on Earth during that time was read as 'infinite'.</li><li>A Sin-Class Rapture called Gluttony was the one responsible for swallowing an ICBM and spitting it back out. Also it shortly died afterwards due to the amount of power unleashed. <em>(Based off Unbreakable Sphere we've learned that Gluttony is a Rapture with many 'mouths', so what swallowed the ICBM was not it's true body but more of like an appendage.)</em></li><li>With the U.F.H. and V.T.C. satisfied with their test results, they order Cinderella to be deployed with the Goddess Squad for a joint operation to attack the Lift to the Space Station.</li><li>Before the operation begins, Cinderella becomes corrupted and proceeds to destroy the facility and attempts to kill off her other squad members. Following this, she then ambushes the Goddess Squad during their operation to attack the Lift.</li><li>2 Months pass since Cinderella was corrupted and Abe has successfully repaired Red Shoes, Siren, Hansel and Gretel by using their spare bodies while hiding from the Raptures attacking the facility.</li><li>Cinderella is officially known as the 1st Heretic Anachiro and branded as a traitor.</li><li>Red Shoes calls for help without Abe's knowledge and Oswald responds as well as brings a small detachment of soldiers. He states that they are under suspicion as traitors and will need to undergo a brain scan along to prove their innocence. Oswald also comments that Hansel and Gretel shouldn't exist, which is reveal that Abe most likely made them in secret.</li><li>Abe, Red Shoes, Siren, Hansel and Gretel successfully escape from Oswald and pursue Anachiro. In an attempt to subdue her, they ultimately fail and Anachiro defeats them all. She then goes after the Goddess Squad which leads into the events of Red Ash's ending.</li></ul>",
        characters: ["Cinderella", "Abe", "Red Shoes", "Siren", "Hansel", "Gretel", "Oswald", "Liliweiss", "Andersen", "Snow White", "Scarlet", "Rapunzel", "Dorothy", "Red Hood"],
        locations: ["Earth"],
        tags: ["Old Tales Squad", "Goddess Squad", "U.F.H.", "V.T.C.", "The Central Government", "The Rapture Queen"],
        image: "images/Event Thumbnails/OT1.png",
        youtube: "",
        connections: []
    },
	
	{
        id: "es-004",
        type: "event_story",
        title: "Red Ash",
        era: "The First Invasion",
        timeline: "96 BC1 (Before Chapter 1)",
        sortOrder: -95,
        summary: "",
        content: "<p><strong>PART 1:</strong></p><ul><li>Takes place 4 years since the Raptures invaded.</li><li>2 years since occasional victories started happening and The United Forces of Humanity started winning more often.</li><li>The most recent addition to the Goddess Squad is Scarlet based off the events of New Year, New Sword.</li><li>During the event, Red Hood is in her post-corruption stages.</li><li>Although the Goddess Squad has achieved victories, other military units have suffered substantial losses and an all-out offensive would be suicide for humanity.</li><li>The ability to mass-produce Nikkes is in the final stages of development and only 200 were made without defects within the last year.</li><li>The Rapture Storm Bringer has already left an impact for air support units.</li><li>Corruption is already well known throughout the war but Red Shoe's variant has significantly impacted Nikkes and left an impression on how devastating it can be. <em>(Old Tales Part 2)</em></li><li>Rapunzel, with the help of V.T.C., begin attempts to cure Red Hood's corruption but with no success.</li><li>The operation to attack the Space Station is underway and the Goddess Squad head to Elysion's 3rd Research Lab to meet up with Cinderella.</li><li>Upon entering the Lab, the facility is in shambles due to being besieged by Raptures. Two 2nd Gen Grimms models are destroyed and Cinderella is missing.</li><li>The Legendary Commander and Liliweiss also discover an amalgamation of Nikke and Rapture that's fused together and deduce that the Raptures initiated this experiment.</li><li>With Cinderella missing, the Goddess Squad is then instructed to go ahead and attack the Lift to the Space Station. As they defeat the surrounding Raptures and ascend the Lift, Cinderella ambushes them and the Goddess Squad narrowly retreats.</li><li>Due to the operation resulting in a failure, humanity begins their retreat into the Ark.</li></ul><p><strong>PART 2:</strong></p><ul><li>Begins roughly 2 months after the battle of the Lift and Red Hood leaving the squad.</li><li>The U.F.H. and the V.T.C. have merged to become The Central Government.</li><li>Cryogenic Sleep is hypothesized to help deter corruption from spreading but it's efficiency is still questionable during this time.</li><li>While wandering the wasteland, Red Hood meets with Oswald and asks to hitchhike on her way to her destination.</li><li>As Oswald and Red Hood travel, a nearby Rapture attack prompts Red Hood to intervene. After successfully rescuing some survivors, Red Hood begins to succumb to corruption but manages to hold off the effects. A little girl named Freesia makes an appearance before heading to the Ark with the other survivors. Red Hood and Oswald share a small bonding moment before they part ways.</li><li>As the Goddess Squad assists with evacuation skirmishes to the Ark, The Legendary Commander and Liliweiss are called back to Central Government Command.</li><li>Red Hood struggles to maintain herself as the corruption begins to take hold, but she successfully staves off the effects and makes her way back to the Goddess Squad to help with protecting the Ark.</li><li>With the absence of both The Legendary Commander and Liliweiss, the Goddess Squad resumes operations of protecting the entrance to the Ark.</li><li>Anachiro unleashes her attack against the Goddess Squad but Red Hood reinforces them, resulting in them claiming victory and Anachiro being defeated.</li><li>After their victory, Red Hood parts ways with the Goddess Squad for good.</li></ul>",
        characters: ["Cinderella", "Oswald", "Liliweiss", "Andersen", "Snow White", "Scarlet", "Rapunzel", "Dorothy", "Red Hood"],
        locations: ["Earth"],
        tags: ["Old Tales Squad", "Goddess Squad", "U.F.H.", "V.T.C.", "The Central Government", "The Rapture Queen"],
        image: "images/Event Thumbnails/RED ASH.png",
        youtube: "",
        connections: []
    },
	
	{
        id: "es-005",
        type: "event_story",
        title: "Ark Guardian Part 1",
        era: "The First Invasion",
        timeline: "96 BC1 (Before Chapter 1)",
        sortOrder: -94,
        summary: "",
        content: "",
        characters: ["Liliweiss", "Andersen", "Snow White", "Scarlet", "Rapunzel", "Dorothy", "Pinne", "Oswald", "Freesia"],
        locations: ["Earth"],
        tags: ["Goddess Squad", "The Central Government", "Heretics"],
        image: "images/Event Thumbnails/Ark_Guardian_Cutscene_01.webp",
        youtube: "",
        connections: []
    },
	
	{
        id: "es-006",
        type: "event_story",
        title: "Old Tales Part 2",
        era: "The First Invasion",
        timeline: "96 BC1 (Before Chapter 1)",
        sortOrder: -93,
        summary: "",
        content: "",
        characters: ["Cinderella", "Abe", "Red Shoes", "Siren", "Hansel", "Gretel", "Oswald", "The Rapture Queen"],
        locations: ["Earth"],
        tags: ["Old Tales Squad", "The Central Government", "The Rapture Queen"],
        image: "images/Event Thumbnails/OT2.png",
        youtube: "",
        connections: []
    },
	
	{
        id: "es-007",
        type: "event_story",
        title: "Ark Guardian Part 2",
        era: "The First Invasion",
        timeline: "96 BC1 (Before Chapter 1)",
        sortOrder: -92,
        summary: "",
        content: "",
        characters: ["Liliweiss", "Andersen", "Snow White", "Scarlet", "Rapunzel", "Dorothy", "Pinne", "Oswald", "Freesia", "Mirror", "Liberalio"],
        locations: ["Earth"],
        tags: ["Old Tales Squad", "The Central Government", "The Rapture Queen"],
        image: "images/Event Thumbnails/Ark_Guardian_Cutscene_08.webp",
        youtube: "",
        connections: []
    },

	{
        id: "es-008",
        type: "event_story",
        title: "Over Zone",
        era: "Post-Ark Sealing",
        timeline: "96 BC1 (Before Chapter 1)",
        sortOrder: -91,
        summary: "",
        content: "",
        characters: ["Snow White", "Scarlet", "Rapunzel", "Dorothy", "Pinne", "Oswald"],
        locations: ["Earth"],
        tags: ["Goddess Squad", "The Central Government", "The Rapture Queen"],
        image: "images/Event Thumbnails/EventScene_OverZone_02.png",
        youtube: "",
        connections: []
    },

	{
        id: "es-009",
        type: "event_story",
        title: "Old Tales Epilogue",
        era: "Post-Ark Sealing",
        timeline: "91 - 74 BC1 (Before Chapter 1)",
        sortOrder: -90,
        summary: "",
        content: "",
        characters: ["Cinderella", "Abe", "Nihilister"],
        locations: ["Earth", "The Ark"],
        tags: ["Old Tales Squad", "The Central Government"],
        image: "images/Event Thumbnails/OT EP.png",
        youtube: "",
        connections: [
			{ target: "es-006", type: "curved" }
		]
    },

	{
        id: "es-010",
        type: "event_story",
        title: "Footstep, Walk, Run Part 1",
        era: "Post-Ark Sealing",
        timeline: "89? - 58 BC1 (Before Chapter 1)",
        sortOrder: -89,
        summary: "",
        content: "",
        characters: ["Rapi", "Red Hood"],
        locations: ["The Ark"],
        tags: [""],
        image: "images/Event Thumbnails/FWR1.png",
        youtube: "",
        connections: []
    },

	{
        id: "ms-pre-4",
        type: "main_story",
        title: "First Reclamation Campaign",
        era: "Post-Ark Sealing",
        timeline: "89? - 80? BC1 (Before Chapter 1)",
        sortOrder: -88,
        summary: "",
        content: "NO KNOWN INFORMATION AS OF NOW",
        locations: ["Earth", "The Ark"],
        tags: ["The Ark", "The Central Government", "First Reclamation War"],
        image: "images/Event Thumbnails/Stage.png",
        youtube: "",
        connections: []
    },

	{
        id: "ss-001",
        type: "side_story",
        title: "Mudfish",
        era: "Post-Ark Sealing",
        timeline: "91 - 70 BC1 (Before Chapter 1)",
        sortOrder: -87,
        summary: "",
        content: "",
        characters: ["Siren", "Leviathan"],
        locations: ["Earth"],
        tags: ["Old Tales Squad", "Dark Matter"],
        image: "images/Event Thumbnails/Mudfish.png",
        youtube: "",
        connections: []
    },
	
	{
        id: "ms-pre-5",
        type: "main_story",
        title: "Second Reclamation Campaign",
        era: "Post-Ark Sealing",
        timeline: "60 BC1 (Before Chapter 1)",
        sortOrder: -60,
        summary: "",
        content: "NO KNOWN INFORMATION AS OF NOW",
        locations: ["Earth", "The Ark"],
        tags: ["The Ark", "The Central Government", "Second Reclamation War"],
        image: "images/Event Thumbnails/Stage.png",
        youtube: "",
        connections: []
    },
	
	{
        id: "es-011",
        type: "event_story",
        title: "Footstep, Walk, Run Part 2 + Red Ash Epilogue",
        era: "Post-Ark Sealing",
        timeline: "58 - 54 BC1 (Before Chapter 1)",
        sortOrder: -59,
        summary: "",
        content: "",
        characters: ["Rapi", "Red Hood"],
        locations: ["The Ark"],
        tags: [""],
        image: "images/Event Thumbnails/FWR2.png",
        youtube: "",
        connections: []
    },

    // === CHAPTER 0 (Year 0, Starting Point) ===
    {
        id: "ms-000",
        type: "main_story",
        chapter: 0,
        title: "Chapter 0: Fall",
        era: "The Beginning",
        timeline: "Year 0 (Undetermined Year but possibly 2XXX)",
        sortOrder: 0,
        isStartPoint: true,  // This marks it as the starting position
        summary: "Chapter 1 content...",
        content: "Full description...",
        characters: ["The Commander", "Marian", "Rapi", "Anis", "Shifty"],
        locations: ["Earth"],
        tags: ["Chapter 0"],
        image: "images/Chapter Thumbnails/Chapter 0.png",
        youtube: "",
        connections: []
    },
    
    // === CHAPTER 1 & ONWARD (Positive sortOrder = right of Chapter 1) ===
    {
        id: "ms-001",
        type: "main_story",
        chapter: 1,
        title: "Chapter 1: Corruption",
        era: "The Beginning",
        timeline: "Within same day as CH 0",
        sortOrder: 10,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Marian", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid"],
        locations: ["Earth", "The Ark"],
        tags: ["Chapter 1"],
        image: "images/Chapter Thumbnails/Chapter 1.png",
        youtube: "",
        connections: []
    },
    
    {
        id: "ms-002",
        type: "main_story",
        chapter: 2,
        title: "Chapter 2: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 20,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 2"],
        image: "images/Chapter Thumbnails/Chapter 2.png",
        youtube: "",
        connections: []
    },

	{
		id: "ms-003",
        type: "main_story",
        chapter: 3,
        title: "Chapter 3: Enlightenment",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 30,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 3"],
        image: "images/Chapter Thumbnails/Chapter 3.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-004",
        type: "main_story",
        chapter: 4,
        title: "Chapter 4: Bouquet",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 40,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 4"],
        image: "images/Chapter Thumbnails/Chapter 4.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-005",
        type: "main_story",
        chapter: 5,
        title: "Chapter 5: Wonderland",
        era: "The Reunion",
        timeline: "Within the same day as CH 2",
        sortOrder: 50,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 5"],
        image: "images/Chapter Thumbnails/Chapter 5.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-006",
        type: "main_story",
        chapter: 6,
        title: "Chapter 6: Pilgrim",
        era: "The Reunion",
        timeline: "Within the same day as CH 2",
        sortOrder: 60,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 6"],
        image: "images/Chapter Thumbnails/Chapter 6.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-007",
        type: "main_story",
        chapter: 7,
        title: "Chapter 7: Reunited",
        era: "The Reunion",
        timeline: "Within the same day as CH 2",
        sortOrder: 70,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 7"],
        image: "images/Chapter Thumbnails/Chapter 7.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-008",
        type: "main_story",
        chapter: 8,
        title: "Chapter 8: Conflict",
        era: "Vapaus",
        timeline: "Within the same day as CH 2",
        sortOrder: 80,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 8"],
        image: "images/Chapter Thumbnails/Chapter 8.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-009",
        type: "main_story",
        chapter: 9,
        title: "Chapter 9: Secret",
        era: "Vapaus",
        timeline: "Within the same day as CH 2",
        sortOrder: 90,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 9"],
        image: "images/Chapter Thumbnails/Chapter 9.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-010",
        type: "main_story",
        chapter: 10,
        title: "Chapter 10: Comrade",
        era: "Vapaus",
        timeline: "Within the same day as CH 2",
        sortOrder: 100,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 10"],
        image: "images/Chapter Thumbnails/Chapter 10.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-011",
        type: "main_story",
        chapter: 11,
        title: "Chapter 11: The Strongest",
        era: "Vapaus",
        timeline: "Within the same day as CH 2",
        sortOrder: 110,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 11"],
        image: "images/Chapter Thumbnails/Chapter 11.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-012",
        type: "main_story",
        chapter: 12,
        title: "Chapter 12: Hometown",
        era: "Vapaus",
        timeline: "Within the same day as CH 2",
        sortOrder: 120,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 12"],
        image: "images/Chapter Thumbnails/Chapter 12.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-013",
        type: "main_story",
        chapter: 13,
        title: "Chapter 13: Copmeback",
        era: "Vapaus",
        timeline: "Within the same day as CH 2",
        sortOrder: 130,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 13"],
        image: "images/Chapter Thumbnails/Chapter 13.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-014",
        type: "main_story",
        chapter: 14,
        title: "Chapter 14: Journey",
        era: "Post-Return of Marian",
        timeline: "Within the same day as CH 2",
        sortOrder: 140,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 14"],
        image: "images/Chapter Thumbnails/Chapter 14.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-015",
        type: "main_story",
        chapter: 15,
        title: "Chapter 15: Luck",
        era: "Post-Return of Marian",
        timeline: "Within the same day as CH 2",
        sortOrder: 150,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 15"],
        image: "images/Chapter Thumbnails/Chapter 15.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-016",
        type: "main_story",
        chapter: 16,
        title: "Chapter 16: Brand",
        era: "Post-Return of Marian",
        timeline: "Within the same day as CH 2",
        sortOrder: 160,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 16"],
        image: "images/Chapter Thumbnails/Chapter 16.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-017",
        type: "main_story",
        chapter: 17,
        title: "Chapter 17: Purpose",
        era: "Post-Return of Marian",
        timeline: "Within the same day as CH 2",
        sortOrder: 170,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 17"],
        image: "images/Chapter Thumbnails/Chapter 17.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-018",
        type: "main_story",
        chapter: 18,
        title: "Chapter 18: Hero",
        era: "Post-Return of Marian",
        timeline: "Within the same day as CH 2",
        sortOrder: 180,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 18"],
        image: "images/Chapter Thumbnails/Chapter 18.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-019",
        type: "main_story",
        chapter: 19,
        title: "Chapter 19: Eden",
        era: "Eden",
        timeline: "Within the same day as CH 2",
        sortOrder: 190,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 19"],
        image: "images/Chapter Thumbnails/Chapter 19.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-020",
        type: "main_story",
        chapter: 20,
        title: "Chapter 20: Fire Dragon",
        era: "Eden",
        timeline: "Within the same day as CH 2",
        sortOrder: 200,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 20"],
        image: "images/Chapter Thumbnails/Chapter 20.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-021",
        type: "main_story",
        chapter: 21,
        title: "Chapter 21: Giant Whale",
        era: "Eden",
        timeline: "Within the same day as CH 2",
        sortOrder: 210,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 21"],
        image: "images/Chapter Thumbnails/Chapter 21.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-022",
        type: "main_story",
        chapter: 22,
        title: "Chapter 22: Invasion",
        era: "Ark Invasion",
        timeline: "Within the same day as CH 2",
        sortOrder: 220,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 22"],
        image: "images/Chapter Thumbnails/Chapter 22.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-023",
        type: "main_story",
        chapter: 230,
        title: "Chapter 23: Prison",
        era: "Ark Invasion",
        timeline: "Within the same day as CH 2",
        sortOrder: 230,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 23"],
        image: "images/Chapter Thumbnails/Chapter 23.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-024",
        type: "main_story",
        chapter: 24,
        title: "Chapter 24: Banishment",
        era: "Ark Invasion",
        timeline: "Within the same day as CH 2",
        sortOrder: 240,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 24"],
        image: "images/Chapter Thumbnails/Chapter 24.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-025",
        type: "main_story",
        chapter: 25,
        title: "Chapter 25: Tracking",
        era: "Ark Invasion",
        timeline: "Within the same day as CH 2",
        sortOrder: 250,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 25"],
        image: "images/Chapter Thumbnails/Chapter 25.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-026",
        type: "main_story",
        chapter: 26,
        title: "Chapter 26: Return",
        era: "Ark Invasion",
        timeline: "Within the same day as CH 2",
        sortOrder: 260,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 26"],
        image: "images/Chapter Thumbnails/Chapter 26.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-027",
        type: "main_story",
        chapter: 27,
        title: "Chapter 27: Exploration",
        era: "The Crystal Region",
        timeline: "Within the same day as CH 2",
        sortOrder: 270,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 27"],
        image: "images/Chapter Thumbnails/Chapter 27.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-028",
        type: "main_story",
        chapter: 28,
        title: "Chapter 28: The Unknown",
        era: "The Crystal Region",
        timeline: "Within the same day as CH 2",
        sortOrder: 280,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 28"],
        image: "images/Chapter Thumbnails/Chapter 28.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-029",
        type: "main_story",
        chapter: 29,
        title: "Chapter 29: Rescue",
        era: "The Crystal Region",
        timeline: "Within the same day as CH 2",
        sortOrder: 290,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 29"],
        image: "images/Chapter Thumbnails/Chapter 29.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-030",
        type: "main_story",
        chapter: 30,
        title: "Chapter 30: Treasure",
        era: "The Crystal Region",
        timeline: "Within the same day as CH 2",
        sortOrder: 300,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 30"],
        image: "images/Chapter Thumbnails/Chapter 30.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-031",
        type: "main_story",
        chapter: 31,
        title: "Chapter 31: Mabeast",
        era: "The Crystal Region",
        timeline: "Within the same day as CH 2",
        sortOrder: 310,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 31"],
        image: "images/Chapter Thumbnails/Chapter 31.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-032",
        type: "main_story",
        chapter: 32,
        title: "Chapter 32: Advance",
        era: "The Crystal Region",
        timeline: "Within the same day as CH 2",
        sortOrder: 320,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 32"],
        image: "images/Chapter Thumbnails/Chapter 32.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-0033",
        type: "main_story",
        chapter: 33,
        title: "Chapter 33: Clash",
        era: "The Crystal Region",
        timeline: "Within the same day as CH 2",
        sortOrder: 330,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 33"],
        image: "images/Chapter Thumbnails/Chapter 33.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-034",
        type: "main_story",
        chapter: 34,
        title: "Chapter 34: Inheritance",
        era: "The Crystal Region",
        timeline: "Within the same day as CH 2",
        sortOrder: 340,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 34"],
        image: "images/Chapter Thumbnails/Chapter 34.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-035",
        type: "main_story",
        chapter: 35,
        title: "Chapter 35: Conversation",
        era: "The Dark Matter Jungle",
        timeline: "Within the same day as CH 2",
        sortOrder: 350,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 35"],
        image: "images/Chapter Thumbnails/Chapter 35.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-036",
        type: "main_story",
        chapter: 36,
        title: "Chapter 36: Betrayal",
        era: "The Dark Matter Jungle",
        timeline: "Within the same day as CH 2",
        sortOrder: 360,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 36"],
        image: "images/Chapter Thumbnails/Chapter 36.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-037",
        type: "main_story",
        chapter: 37,
        title: "Chapter 37: Struggle",
        era: "The Dark Matter Jungle",
        timeline: "Within the same day as CH 2",
        sortOrder: 370,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 37"],
        image: "images/Chapter Thumbnails/Chapter 37.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-038",
        type: "main_story",
        chapter: 38,
        title: "Chapter 38: Gluttony",
        era: "The Dark Matter Jungle",
        timeline: "Within the same day as CH 2",
        sortOrder: 380,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 38"],
        image: "images/Chapter Thumbnails/Chapter 38.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-039",
        type: "main_story",
        chapter: 39,
        title: "Chapter 39: Gene",
        era: "The Consort Gene",
        timeline: "Within the same day as CH 2",
        sortOrder: 390,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 39"],
        image: "images/Chapter Thumbnails/Chapter 39.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-040",
        type: "main_story",
        chapter: 40,
        title: "Chapter 40: Choice",
        era: "The Consort Gene",
        timeline: "Within the same day as CH 2",
        sortOrder: 400,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 40"],
        image: "images/Chapter Thumbnails/Chapter 40.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-041",
        type: "main_story",
        chapter: 41,
        title: "Chapter 41: Birth",
        era: "The Consort Gene",
        timeline: "Within the same day as CH 2",
        sortOrder: 410,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 41"],
        image: "images/Chapter Thumbnails/EventScene_Chap_41_06.webp",
        youtube: "",
        connections: []
	},

	{
		id: "ms-042",
        type: "main_story",
        chapter: 42,
        title: "Chapter 42: Only One",
        era: "The Consort Gene",
        timeline: "Within the same day as CH 2",
        sortOrder: 420,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 42"],
        image: "images/Chapter Thumbnails/EventScene_Chap_42_09.webp",
        youtube: "",
        connections: []
	},

	{
		id: "ms-043",
        type: "main_story",
        chapter: 43,
        title: "Chapter 43: Key",
        era: "The Third Reclamation War",
        timeline: "Within the same day as CH 2",
        sortOrder: 430,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 43"],
        image: "images/Chapter Thumbnails/EventScene_Chap_43_02_4.webp",
        youtube: "",
        connections: []
	},

	{
		id: "ms-044",
        type: "main_story",
        chapter: 44,
        title: "Chapter 44: Path",
        era: "The Third Reclamation War",
        timeline: "Within the same day as CH 2",
        sortOrder: 440,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 44"],
        image: "images/Chapter Thumbnails/EventScene_Chap_44_04.webp",
        youtube: "",
        connections: []
	},
];
