const ENTRIES = [
    // === PRE-CHAPTER 1 (Negative sortOrder = left of Chapter 1) ===
    {
        id: "ms-pre-1",
        type: "main_story",
        title: "Pre-First Invasion",
        era: "Pre-First Invasion",
        timeline: "+100 BC1 (Before Chapter 1)",
        sortOrder: -110,
        summary: "",
        content: "The World was similar to what we know now in real life, but slightly more technologically advanced. <ul><li>Manufactures such as Elysion, Missilis and Tetra existed but no exact detail on how big they were aside from Relics stating them to be enterprises. (Early Relics called them by Elysion Enterprises, Missilis Industries, and Tetra Entertainment).</li><li>Military strength similar to IRL or at least slightly more advanced.</li><li>Einkk stated that she is roughly 20 years old (Memory of Goddess secret cutscene) which puts her origins during Pre-First Invasion but no other specifics on who or what made her.</li><li>Based off Chapter 43, the VTC has existed for a long time and made many strides in the advancement of technology even before the creation of Nikkes.</li></ul>",
        locations: ["Earth"],
        tags: ["Humanity", "V.T.C."],
        image: "images/Chapter Thumbnails/Sky2.png",
        youtube: "",
        connections: []
    },
    {
        id: "ms-pre-2",
        type: "main_story",
        title: "The First Invasion",
        era: "The First Invasion",
        timeline: "100 BC1 (Before Chapter 1)",
        sortOrder: -100,
        summary: "",
        content: "Raptures began to invade multiple countries in hordes causing devastation. <ul><li><strong>Theories concluded that Raptures originated from the Space Station.</strong> Theories were reinforced when it was discovered that the Raptures targeted various shuttle-launch locations around the world during the initial attack. <em>(RED ASH INFO)</em></li><li>Initial military response was ill-equipped and resulted in many casualties.</li><li>The use of thermonuclear weapons had little to no effect and some instances had Raptures firing it back at humans. <em>(OLD TALES)</em> <em>(GLUTTONY)</em></li><li>As a result of all these attacks, <strong>The United Forces of Humanity</strong> was formed to be a combined effort against the Rapture threat.</li><li>No information on <strong>VTC</strong> aside from it being a medical institute run by the church but it can be assumed that the same happened like the UFH.</li><li>The first Nikke, <strong>Liliweiss</strong>, was created which followed the 1st and 2nd Generation Grimms models as well as the Mass-Produced models.</li><li>Previously a mercenary, <strong>The Legendary Commander</strong> began to acquire fame and eventually became the commander for the newly formed Goddess Squad.</li><li>Humanity began to win against Raptures as Nikkes proved to be an effective weapon, but due to that Raptures began to evolve.</li></ul>",
		locations: ["Earth", "Space Station"],
        tags: ["Humanity", "U.F.H.", "V.T.C."],
        image: "images/Chapter Thumbnails/SpaceElevator.png",
        youtube: "",
        connections: [
            { target: "ms-pre-1", type: "curved" }
        ]
    },

    {
        id: "ms-pre-3",
        type: "main_story",
        title: "Death of the First Grimms Model",
        era: "The First Invasion",
        timeline: "Unknown Time BC1 (Before Chapter 1)",
        sortOrder: -99,
        summary: "",
        content: "<ul><li>No specific info on <strong>Grimms Model 1</strong> yet. <em>(Red Ash Relic)</em></li><li><strong>Dorothy</strong> joins Goddess Squad as <strong>Grimms Model 2</strong>. Daughter of a politician, she wants the world to go back to the way it was before the Rapture Invasion.</li><li><strong>Rapunzel</strong> joins Goddess Squad as <strong>Grimms Model 3</strong>. A former leading candidate for the papacy, she wanted to become a beacon of hope for mankind and joined up.</li><li><strong>Snow White</strong> joins Goddess Squad as <strong>Grimms Model 4</strong>. Introduced herself to the squad during one of their battles by mending their weapons. Has met <strong>Liliweiss</strong> before but not stated when exactly. Initially wasn't confident enough to properly meet them and shut herself in her room crafting weapons.</li><li><strong>Red Hood</strong> joins Goddess Squad as <strong>Grimms Model 5</strong>. Making a dramatic entrance by appearing out of a box, Red Hood's introduction to the squad left a significant impression on them.</li></ul>",
        locations: ["Earth"],
        tags: ["Humanity", "U.F.H.", "V.T.C.", "Nikke", "Goddess Squad"],
        image: "images/Event Thumbnails/Grassland.png",
        youtube: "",
        connections: []
    },
	
	{
        id: "es-001",
        type: "event_story",
        title: "New Year New Sword",
        era: "The First Invasion",
        timeline: "99 - 96 BC1 (Before Chapter 1)",
        sortOrder: -98,
        summary: "",
        content: "<ul><li>Set before the events of <strong>Red Ash</strong> and at some point after the <strong>Goddess Squad</strong> is formed.</li><li><strong>Scarlet</strong> and her sister <strong>Rose</strong> are among the few selected for an experimental Nikke squad called <strong>Melee Squad</strong> for infiltration and reclamation.</li><li><strong>Rose</strong> is selected to be the squad leader for having the highest test scores.</li><li>Their first mission resulted in a resounding success with zero casualties.</li><li>As more missions continued to succeed, more Nikkes were lost. Some Nikkes were even prone to <strong>mind switches</strong> due to attacking <strong>Raptures</strong> in head-on confrontations.</li><li>Eventually the missions became more difficult and with each mission came greater casualties. Including both <strong>Rose</strong> and <strong>Scarlet</strong>, the <strong>Melee Squad</strong> is down to six members.</li><li><strong>Rose</strong> begins to question the validity of their circumstances and goes to question the commander. She discovers that the original objective was to slowly kill off the <strong>Melee Squad</strong> until only one was left which then would succeed to becoming a <strong>Grimms Model</strong>.</li><li><strong>Rose</strong> being angered by the deception, kills the commander and another one of their squadmates. She states that she covered herself with a blindfold and imagined them to be <strong>Raptures</strong> in order to prevent a <strong>mind switch</strong> from happening.</li><li>Seeing the destruction that <strong>Rose</strong> had caused, <strong>Scarlet</strong> had no choice but to kill her sister. Stabbing <strong>Rose</strong> through her core, she killed her sister but as well as finding out that <strong>Rose</strong> intended to kill herself off to save <strong>Scarlet</strong>.</li><li>As time passed the <strong>UFH</strong> became aware of what transpired and deemed the project a failure, citing that it was internal conflict that had the Nikkes kill each other.</li><li><strong>Scarlet</strong> took <strong>Rose's</strong> sword, <strong>Fleetly Fading</strong>, since her original sword was taken along with <strong>Rose's</strong> body. Although <strong>Fleetly Fading</strong> was broken, <strong>Scarlet</strong> met a blacksmith that could fix it by using <strong>Rose's Core</strong>.</li></ul>",
        characters: ["Scarlet", "Rose"],
        locations: ["Earth"],
        tags: ["New Year New Sword", "Melee Squad", "Scarlet", "Rose"],
        image: "images/Event Thumbnails/NYNS.png",
        youtube: "",
        connections: []
    },

	{
        id: "es-002",
        type: "event_story",
        title: "Old Tales Part 1",
        era: "The First Invasion",
        timeline: "96 BC1 (Before Chapter 1)",
        sortOrder: -97,
        summary: "",
        content: "",
        characters: ["Cinderella", "Abe", "Red Shoes", "Siren", "Hansel", "Gretel", "Oswald", "The Rapture Queen", "Liliweiss", "Andersen", "Snow White", "Scarlet", "Rapunzel", "Dorothy", "Red Hood"],
        locations: ["Earth"],
        tags: ["Old Tales Squad", "Goddess Squad", "U.F.H.", "V.T.C.", "The Central Government", "The Rapture Queen"],
        image: "images/Event Thumbnails/OT1.png",
        youtube: "",
        connections: []
    },
	
	{
        id: "es-003",
        type: "event_story",
        title: "Red Ash",
        era: "The First Invasion",
        timeline: "96 BC1 (Before Chapter 1)",
        sortOrder: -96,
        summary: "",
        content: "",
        characters: ["Cinderella", "Abe", "Red Shoes", "Siren", "Hansel", "Gretel", "Oswald", "The Rapture Queen", "Liliweiss", "Andersen", "Snow White", "Scarlet", "Rapunzel", "Dorothy", "Red Hood"],
        locations: ["Earth"],
        tags: ["Old Tales Squad", "Goddess Squad", "U.F.H.", "V.T.C.", "The Central Government", "The Rapture Queen"],
        image: "images/Event Thumbnails/RED ASH.png",
        youtube: "",
        connections: []
    },

	{
        id: "es-004",
        type: "event_story",
        title: "Red Ash Epilogue",
        era: "Post-Ark Sealing",
        timeline: "58 BC1 (Before Chapter 1)",
        sortOrder: -91,
        summary: "",
        content: "",
        characters: ["Cinderella", "Abe", "Red Shoes", "Siren", "Hansel", "Gretel", "Oswald", "The Rapture Queen", "Liliweiss", "Andersen", "Snow White", "Scarlet", "Rapunzel", "Dorothy", "Red Hood"],
        locations: ["Earth"],
        tags: ["Old Tales Squad", "Goddess Squad", "U.F.H.", "V.T.C.", "The Central Government", "The Rapture Queen"],
        image: "images/Event Thumbnails/FWR2.png",
        youtube: "",
        connections: []
    },
	
	{
        id: "es-005",
        type: "event_story",
        title: "Ark Guardian Part 1",
        era: "The First Invasion",
        timeline: "96 BC1 (Before Chapter 1)",
        sortOrder: -94,
        summary: "",
        content: "",
        characters: ["Liliweiss", "Andersen", "Snow White", "Scarlet", "Rapunzel", "Dorothy", "Pinne", "Oswald", "Freesia"],
        locations: ["Earth"],
        tags: ["Goddess Squad", "The Central Government", "Heretics"],
        image: "images/Event Thumbnails/Ark_Guardian_Cutscene_01.webp",
        youtube: "",
        connections: []
    },
	
	{
        id: "es-006",
        type: "event_story",
        title: "Old Tales Part 2",
        era: "The First Invasion",
        timeline: "96 BC1 (Before Chapter 1)",
        sortOrder: -93,
        summary: "",
        content: "",
        characters: ["Cinderella", "Abe", "Red Shoes", "Siren", "Hansel", "Gretel", "Oswald", "The Rapture Queen"],
        locations: ["Earth"],
        tags: ["Old Tales Squad", "The Central Government", "The Rapture Queen"],
        image: "images/Event Thumbnails/OT2.png",
        youtube: "",
        connections: []
    },

	{
        id: "es-007",
        type: "event_story",
        title: "Old Tales Epilogue",
        era: "Post-Ark Sealing",
        timeline: "91 - 74 BC1 (Before Chapter 1)",
        sortOrder: -90,
        summary: "",
        content: "",
        characters: ["Cinderella", "Abe", "Nihilister"],
        locations: ["Earth", "The Ark"],
        tags: ["Old Tales Squad", "The Central Government"],
        image: "images/Event Thumbnails/OT EP.png",
        youtube: "",
        connections: [
			{ target: "es-006", type: "curved" }
		]
    },
	
	{
        id: "es-008",
        type: "event_story",
        title: "Ark Guardian Part 2",
        era: "The First Invasion",
        timeline: "96 BC1 (Before Chapter 1)",
        sortOrder: -92,
        summary: "",
        content: "",
        characters: ["Liliweiss", "Andersen", "Snow White", "Scarlet", "Rapunzel", "Dorothy", "Pinne", "Oswald", "Freesia", "Mirror", "Liberalio"],
        locations: ["Earth"],
        tags: ["Old Tales Squad", "The Central Government", "The Rapture Queen"],
        image: "images/Event Thumbnails/Ark_Guardian_Cutscene_08.webp",
        youtube: "",
        connections: []
    },

	{
        id: "es-009",
        type: "event_story",
        title: "Over Zone",
        era: "Post-Ark Sealing",
        timeline: "96 BC1 (Before Chapter 1)",
        sortOrder: -95,
        summary: "",
        content: "",
        characters: ["Snow White", "Scarlet", "Rapunzel", "Dorothy", "Pinne", "Oswald"],
        locations: ["Earth"],
        tags: ["Goddess Squad", "The Central Government", "The Rapture Queen"],
        image: "images/Event Thumbnails/EventScene_OverZone_02.png",
        youtube: "",
        connections: []
    },
	
	{
        id: "es-010",
        type: "event_story",
        title: "Footstep, Walk, Run Part 1",
        era: "Post-Ark Sealing",
        timeline: "89? - 58 BC1 (Before Chapter 1)",
        sortOrder: -88,
        summary: "",
        content: "",
        characters: ["Rapi", "Red Hood"],
        locations: ["The Ark"],
        tags: [""],
        image: "images/Event Thumbnails/FWR1.png",
        youtube: "",
        connections: []
    },
	
	{
        id: "es-011",
        type: "event_story",
        title: "Footstep, Walk, Run Part 2",
        era: "Post-Ark Sealing",
        timeline: "58 - 54 BC1 (Before Chapter 1)",
        sortOrder: -59,
        summary: "",
        content: "",
        characters: ["Rapi", "Red Hood"],
        locations: ["The Ark"],
        tags: [""],
        image: "images/Event Thumbnails/FWR2.png",
        youtube: "",
        connections: []
    },
	
    {
        id: "ms-pre-4",
        type: "main_story",
        title: "First Reclamation Campaign",
        era: "Post-Ark Sealing",
        timeline: "89? - 80? BC1 (Before Chapter 1)",
        sortOrder: -89,
        summary: "",
        content: "NO KNOWN INFORMATION AS OF NOW",
        locations: ["Earth", "The Ark"],
        tags: ["The Ark", "The Central Government", "Nikke", "First Reclamation War"],
        image: "images/Event Thumbnails/Stage.png",
        youtube: "",
        connections: []
    },

    {
        id: "ms-pre-5",
        type: "main_story",
        title: "Second Reclamation Campaign",
        era: "Post-Ark Sealing",
        timeline: "60 BC1 (Before Chapter 1)",
        sortOrder: -60,
        summary: "",
        content: "NO KNOWN INFORMATION AS OF NOW",
        locations: ["Earth", "The Ark"],
        tags: ["The Ark", "The Central Government", "Nikke", "Second Reclamation War"],
        image: "images/Event Thumbnails/Stage.png",
        youtube: "",
        connections: []
    },

	{
        id: "ss-001",
        type: "side_story",
        title: "Mudfish",
        era: "Post-Ark Sealing",
        timeline: "91 - 70 BC1 (Before Chapter 1)",
        sortOrder: -87,
        summary: "",
        content: "",
        characters: ["Siren", "Leviathan"],
        locations: ["Earth"],
        tags: ["Old Tales Squad", "Dark Matter"],
        image: "images/Event Thumbnails/Mudfish.png",
        youtube: "",
        connections: []
    },
    
    // === CHAPTER 0 (Year 0, Starting Point) ===
    {
        id: "ms-000",
        type: "main_story",
        chapter: 0,
        title: "Chapter 0: Fall",
        era: "The Beginning",
        timeline: "Year 0 (Undetermined Year but possibly 2XXX)",
        sortOrder: 0,
        isStartPoint: true,  // This marks it as the starting position
        summary: "Chapter 1 content...",
        content: "Full description...",
        characters: ["The Commander", "Marian", "Rapi", "Anis", "Shifty"],
        locations: ["Earth"],
        tags: ["Chapter 0"],
        image: "images/Chapter Thumbnails/img_album_chapter00.png",
        youtube: "",
        connections: []
    },
    
    // === CHAPTER 1 & ONWARD (Positive sortOrder = right of Chapter 1) ===
    {
        id: "ms-001",
        type: "main_story",
        chapter: 1,
        title: "Chapter 1: Corruption",
        era: "The Beginning",
        timeline: "Within same day as CH 0",
        sortOrder: 10,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Marian", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid"],
        locations: ["Earth", "The Ark"],
        tags: ["Chapter 1"],
        image: "images/Chapter Thumbnails/img_album_chapter01.png",
        youtube: "",
        connections: []
    },
    
    {
        id: "ms-002",
        type: "main_story",
        chapter: 2,
        title: "Chapter 2: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 20,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 2"],
        image: "images/Chapter Thumbnails/img_album_chapter02.png",
        youtube: "",
        connections: []
    },

	{
		id: "ms-003",
        type: "main_story",
        chapter: 3,
        title: "Chapter 3: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 30,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 3"],
        image: "images/Chapter Thumbnails/img_album_chapter03.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-004",
        type: "main_story",
        chapter: 4,
        title: "Chapter 4: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 40,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 4"],
        image: "images/Chapter Thumbnails/img_album_chapter04.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-005",
        type: "main_story",
        chapter: 5,
        title: "Chapter 5: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 50,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 5"],
        image: "images/Chapter Thumbnails/img_album_chapter05.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-006",
        type: "main_story",
        chapter: 6,
        title: "Chapter 6: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 60,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 6"],
        image: "images/Chapter Thumbnails/img_album_chapter06.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-007",
        type: "main_story",
        chapter: 7,
        title: "Chapter 7: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 70,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 7"],
        image: "images/Chapter Thumbnails/img_album_chapter07.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-008",
        type: "main_story",
        chapter: 8,
        title: "Chapter 8: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 80,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 8"],
        image: "images/Chapter Thumbnails/img_album_chapter08.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-009",
        type: "main_story",
        chapter: 9,
        title: "Chapter 9: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 90,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 9"],
        image: "images/Chapter Thumbnails/img_album_chapter09.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-010",
        type: "main_story",
        chapter: 10,
        title: "Chapter 10: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 100,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 10"],
        image: "images/Chapter Thumbnails/img_album_chapter10.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-011",
        type: "main_story",
        chapter: 11,
        title: "Chapter 11: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 110,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 11"],
        image: "images/Chapter Thumbnails/img_album_chapter11.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-012",
        type: "main_story",
        chapter: 12,
        title: "Chapter 12: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 120,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 12"],
        image: "images/Chapter Thumbnails/img_album_chapter12.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-013",
        type: "main_story",
        chapter: 13,
        title: "Chapter 13: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 130,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 13"],
        image: "images/Chapter Thumbnails/img_album_chapter13.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-014",
        type: "main_story",
        chapter: 14,
        title: "Chapter 14: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 140,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 14"],
        image: "images/Chapter Thumbnails/img_album_chapter14.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-015",
        type: "main_story",
        chapter: 15,
        title: "Chapter 15: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 150,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 15"],
        image: "images/Chapter Thumbnails/img_album_chapter15.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-016",
        type: "main_story",
        chapter: 16,
        title: "Chapter 16: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 160,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 16"],
        image: "images/Chapter Thumbnails/img_album_chapter16.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-017",
        type: "main_story",
        chapter: 17,
        title: "Chapter 17: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 170,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 17"],
        image: "images/Chapter Thumbnails/img_album_chapter17.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-018",
        type: "main_story",
        chapter: 18,
        title: "Chapter 18: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 180,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 18"],
        image: "images/Chapter Thumbnails/img_album_chapter18.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-019",
        type: "main_story",
        chapter: 19,
        title: "Chapter 19: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 190,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 19"],
        image: "images/Chapter Thumbnails/img_album_chapter19.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-020",
        type: "main_story",
        chapter: 20,
        title: "Chapter 20: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 200,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 20"],
        image: "images/Chapter Thumbnails/img_album_chapter20.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-021",
        type: "main_story",
        chapter: 21,
        title: "Chapter 21: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 210,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 21"],
        image: "images/Chapter Thumbnails/img_album_chapter21.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-022",
        type: "main_story",
        chapter: 22,
        title: "Chapter 22: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 220,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 22"],
        image: "images/Chapter Thumbnails/img_album_chapter22.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-023",
        type: "main_story",
        chapter: 230,
        title: "Chapter 23: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 230,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 23"],
        image: "images/Chapter Thumbnails/img_album_chapter23.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-024",
        type: "main_story",
        chapter: 24,
        title: "Chapter 24: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 240,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 24"],
        image: "images/Chapter Thumbnails/img_album_chapter24.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-025",
        type: "main_story",
        chapter: 25,
        title: "Chapter 25: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 250,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 25"],
        image: "images/Chapter Thumbnails/img_album_chapter25.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-026",
        type: "main_story",
        chapter: 26,
        title: "Chapter 26: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 260,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 26"],
        image: "images/Chapter Thumbnails/img_album_chapter26.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-027",
        type: "main_story",
        chapter: 27,
        title: "Chapter 27: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 270,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 27"],
        image: "images/Chapter Thumbnails/img_album_chapter27.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-028",
        type: "main_story",
        chapter: 28,
        title: "Chapter 28: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 280,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 28"],
        image: "images/Chapter Thumbnails/img_album_chapter28.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-029",
        type: "main_story",
        chapter: 29,
        title: "Chapter 29: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 290,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 29"],
        image: "images/Chapter Thumbnails/img_album_chapter29.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-030",
        type: "main_story",
        chapter: 30,
        title: "Chapter 30: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 300,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 30"],
        image: "images/Chapter Thumbnails/img_album_chapter30.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-031",
        type: "main_story",
        chapter: 31,
        title: "Chapter 31: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 310,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 31"],
        image: "images/Chapter Thumbnails/img_album_chapter31.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-032",
        type: "main_story",
        chapter: 32,
        title: "Chapter 32: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 320,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 32"],
        image: "images/Chapter Thumbnails/img_album_chapter32.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-0033",
        type: "main_story",
        chapter: 33,
        title: "Chapter 33: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 330,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 33"],
        image: "images/Chapter Thumbnails/img_album_chapter33.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-034",
        type: "main_story",
        chapter: 34,
        title: "Chapter 34: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 340,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 34"],
        image: "images/Chapter Thumbnails/img_album_chapter34.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-035",
        type: "main_story",
        chapter: 35,
        title: "Chapter 35: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 350,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 35"],
        image: "images/Chapter Thumbnails/img_album_chapter35.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-036",
        type: "main_story",
        chapter: 36,
        title: "Chapter 36: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 360,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 36"],
        image: "images/Chapter Thumbnails/img_album_chapter36.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-037",
        type: "main_story",
        chapter: 37,
        title: "Chapter 37: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 370,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 37"],
        image: "images/Chapter Thumbnails/img_album_chapter37.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-038",
        type: "main_story",
        chapter: 38,
        title: "Chapter 38: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 380,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 38"],
        image: "images/Chapter Thumbnails/img_album_chapter38.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-039",
        type: "main_story",
        chapter: 39,
        title: "Chapter 39: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 390,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 39"],
        image: "images/Chapter Thumbnails/img_album_chapter39.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-040",
        type: "main_story",
        chapter: 40,
        title: "Chapter 40: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 400,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 40"],
        image: "images/Chapter Thumbnails/img_album_chapter40.png",
        youtube: "",
        connections: []
	},

	{
		id: "ms-041",
        type: "main_story",
        chapter: 41,
        title: "Chapter 41: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 410,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 41"],
        image: "images/Chapter Thumbnails/EventScene_Chap_41_06.webp",
        youtube: "",
        connections: []
	},

	{
		id: "ms-042",
        type: "main_story",
        chapter: 42,
        title: "Chapter 42: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 420,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 42"],
        image: "images/Chapter Thumbnails/EventScene_Chap_42_09.webp",
        youtube: "",
        connections: []
	},

	{
		id: "ms-043",
        type: "main_story",
        chapter: 43,
        title: "Chapter 43: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 430,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 43"],
        image: "images/Chapter Thumbnails/EventScene_Chap_43_02_4.webp",
        youtube: "",
        connections: []
	},

	{
		id: "ms-044",
        type: "main_story",
        chapter: 44,
        title: "Chapter 44: Identification",
        era: "The Beginning",
        timeline: "Within the same day as CH 2",
        sortOrder: 440,
        summary: "Content...",
        content: "Full description...",
        characters: ["The Commander", "Rapi", "Anis", "Neon", "Shifty", "Andersen", "Ingrid", "Syuen", "Yuni", "Mihara"],
        locations: ["The Surface", "The Ark", "The Outpost"],
        tags: ["Chapter 44"],
        image: "images/Chapter Thumbnails/EventScene_Chap_44_04.webp",
        youtube: "",
        connections: []
	},
];
